---
- name: Install and configure Wazuh Agent
  hosts: all
  become: yes
  tasks:
    - name: Download Wazuh Agent package
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_amd64.deb
        dest: /tmp/wazuh-agent_4.9.2-1_amd64.deb

    - name: Set WAZUH environment variables
      ansible.builtin.shell:
        cmd: |
          export WAZUH_MANAGER="10.1.20.195"
          export WAZUH_AGENT_GROUP="default"
          export WAZUH_AGENT_NAME="tpot"
          dpkg -i /tmp/wazuh-agent_4.9.2-1_amd64.deb
        executable: /bin/bash

    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable Wazuh Agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Start Wazuh Agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started
    
    - name: Set read permissions recursively for /home/uthman/tpotce/data/
      ansible.builtin.file:
        path: "/home/uthman/tpotce/data/"
        state: directory
        mode: "0755"
        recurse: yes

    - name: Set read permissions recursively for /opt/vulhub-logs/ (only if it exists)
      ansible.builtin.file:
        path: "/opt/vulhub-logs/"
        state: directory
        mode: "0755"
        recurse: yes
