---
#####################################
# T-Pot - Prepare for Docker Engine #
#####################################

- name: T-Pot - Prepare for and install Docker Engine
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Remove distribution based Docker packages and podman-docker (Debian)
      package:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
          - podman-docker
          - podman
        state: absent
        update_cache: yes
      when: ansible_distribution in "Debian"

    - name: Add folder for Docker Engine GPG key (Debian)
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
      when: ansible_distribution in "Debian"

    - name: Download Docker Engine GPG key (Debian)
      get_url:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        dest: /etc/apt/keyrings/docker
        mode: 0755
      when: ansible_distribution in "Debian"

    - name: Decrypt Docker Engine GPG key (Debian)
      shell: gpg --dearmor /etc/apt/keyrings/docker
      args:
        creates: /etc/apt/keyrings/docker.gpg
      when: ansible_distribution in "Debian"

    - name: Add Docker Engine repository (Debian)
      apt_repository:
        filename: docker
        repo: "deb [arch={{ ansible_architecture | replace('aarch64', 'arm64') | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      when: ansible_distribution in "Debian"

#################################
# T-Pot - Install Docker Engine #
#################################

- name: T-Pot - Install Docker Engine
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install Docker Engine packages (Debian)
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes
      when: ansible_distribution in "Debian"


    - name: Stop Docker (All)
      service:
        name: docker
        state: stopped
        enabled: false
      when: ansible_distribution in "Debian"
